### ISSUE TITLE
Question: Multiple CHIPTools librairies

### ISSUE THREAD

**Issue by OlivierGre** [google-home/sample-apps-for-matter-android#166]
On my Android phone (used for development), I have Matter CHIPTool App, Google Home and Google Home Sample App installed.

If I'm correct, those 3 applications are relying on the same libraries (CHIPController.jar for the applicative part and libCHIPController.so for the native part). 

The 3 libs "libCHIPController.so" might be different so I'm wondering how it is working and if we may have interferences between those 3 versions. 

Thank you for your highlights!

**Comment by OlivierGre** [comment]
I can see that the Android phone has some native code executed when it receives the BLE advertizing of a Matter device (for example it sends a PBKDFParamRequest). I'm wondering how this is living together with the native code present in Google Home Sample App.

**Comment by OlivierGre** [comment]
I have uninstalled the CHIPTool App and Google Home but I still have something unclear about the duplicated code in Google Home Sample App and in Android native code.

Android native code has some code to detect the BLE advertizing of Matter devices and to start the Matter Commissioning. I don't understand how this is living together with  Google Home Sample App (which also has code for the same). If both try to initiate the commissioning and send their own PBKDFParamRequest, how can it work?

Here is the trace when Matter Commissioning is started by Android native code:
`2023-09-05 16:54:00.709 15137-15137 native                  pid-15137                            I  I0000 00:00:1693925640.708980   15137 chip_logging.cc:17] CHIP: EM: <<< [E:13931i S:0 M:193057879] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest)`

And here is the trace from "libCHIPController.so" embedded in homesampleapp:
`2023-09-05 16:54:26.377 21276-21276 EM                      com.google.homesampleapp.default     D  <<< [E:26031i S:0 M:6547496] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest) --- Len 52`

Thank you

**Comment by OlivierGre** [comment]
I can see in the logcat that, when my Matter device is switched on, the BLE advertizing is detected by android native code and Matter commissioning is done. 

Then I can see that "onCommissioningRequested" of google.homesampleapp is called and another commissioning is done for the sample app. A comment in the source code says: 
` // Perform commissioning on custom fabric for the sample app.`

**Comment by OlivierGre** [comment]
If my understanding is correct, the first commissioning (the native one) is done by Google Play service and the second commissioning is done by Google Home Same App. 

The first commissioning brings the network connectivity to the Matter device (it can communicates over Thread). 
The second commissioning allows Google Home Same App to communicate with the device. This second commissioning relies on the existing network (Wifi + Thread) to communicate with the device.

**Comment by pierredelisle** [comment]
> If my understanding is correct, the first commissioning (the native one) is done by Google Play service and the second commissioning is done by Google Home Same App.

Correct.
When using the Google Home commissioning APIs (which the sample app uses), commissioning if first done on a "local Android fabric", and then the API yields control back to the sample App to commission to its own private fabric.

The sample app needs to have its own fabric to be able to control the Matter devices, since currently the Google Home APIs do not support controlling Matter devices. The sample app relies on the Matter SDK coming from connectedhomeip (at the CSA) to support controls/subscriptions on Matter devices.

See the [README](https://github.com/google-home/sample-apps-for-matter-android/blob/main/README.md) file:
Third-Party Ecosystem (3p-ecosystem) If your organization supports its own ecosystem of smart devices, then the "3p-ecosystem" sample application is for you. It leverages the commissioning, device sharing, and discovery APIs offered in the [Google Home Mobile SDK](https://developers.home.google.com/mobile-sdk). Note that the sample application provides supports only for a demo fabric based on the Matter SDK. If you plan to make your application available in production, then you will have to deal with the complexity of managing in a secure fashion your own Matter fabric.

**Comment by OlivierGre** [comment]
@pierredelisle Thanks for those explanations.
