### ISSUE TITLE
Uploading CHIP Maven artifacts

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-apps-for-matter-android#80]
I am trying to figure how to do this, but I am not succeeding.

https://stackoverflow.com/questions/75400578/uploading-android-native-artifacts-to-maven

**Comment by tetedoie** [comment]
I'm able to import the maven artifact you published on Gitlab into GHSAFM. 

In [settings.gradle](https://github.com/google-home/sample-app-for-matter-android/blob/main/settings.gradle)
Add the repository under `dependencyResolutionManagement` like

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://gitlab.com/api/v4/projects/43346074/packages/maven'
        }
    }
}
```
Then in [app/build.gradle](https://github.com/google-home/sample-app-for-matter-android/blob/main/app/build.gradle) add the dependency into the dependencies block like
```
dependencies {
   [...]
    implementation 'com.lowpan.m2:CHIPController:1.0.0'
}
```

When, you do a Gradle sync, you'll see that the artifact is downloaded. Gradle will start complaining about duplicate classes 
between the maven artifact and the local jar like 
```
Duplicate class chip.devicecontroller.model.NodeState found in modules CHIPController (CHIPController.jar) and CHIPController-1.0 (com.lowpan.m2:CHIPController:1.0.0)
```
You can delete the local [CHIPController.jar](https://github.com/google-home/sample-app-for-matter-android/blob/main/app/third_party/connectedhomeip/libs/CHIPController.jar) to solve it.

Then the app will compile but crash immediately with the following stack-trace : 
 
```
         Caused by: chip.devicecontroller.ChipDeviceControllerException: ../../src/lib/support/JniReferences.cpp:124: Error 0x00000702
                                                                                                    	at chip.devicecontroller.ChipDeviceController.newDeviceController(Native Method)
                                                                                                    	at chip.devicecontroller.ChipDeviceController.<init>(ChipDeviceController.java:56)
                                                                                                    	at com.google.homesampleapp.chip.ChipClient$chipDeviceController$2.invoke(ChipClient.kt:61)
                                                                                                    	at com.google.homesampleapp.chip.ChipClient$chipDeviceController$2.invoke(ChipClient.kt:51)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.google.homesampleapp.chip.ChipClient.getChipDeviceController(ChipClient.kt:51)
                                                                                                    	at com.google.homesampleapp.screens.home.HomeFragment.setDeviceAttestationDelegate(HomeFragment.kt:432)
                                                                                                    	at com.google.homesampleapp.screens.home.HomeFragment.onCreate(HomeFragment.kt:152)

```

**Comment by tetedoie** [comment]
It's crashing just because the native .so files I have locally aren't the same ones used when publishing your maven artifact. When I publish locally the maven artifact or if I checkout v1.3.0 and use your published artifact, it's not crashing anymore. 

I'm looking how to package the so files. We have to keep in mind that this work should be done in the `connectedhomeip` repository not this repository if we want to avoid manual update and LFS and it seems that the `connectedhomeip` repository doesn't use Gradle so we might have to consider something else than the Gradle `maven-publish` plugin to do the publication.

**Comment by tetedoie** [comment]
The `connectedhomeip` repository [is actually using Gradle](https://github.com/project-chip/connectedhomeip/tree/master/third_party/android_deps) already

**Comment by tetedoie** [comment]
The simplest approach to package the `.so` files I found is to use an android library module, add the `jniLibs` folder as `jniLibs.srcDir`. Then publishing the `aar`. The resulting `aar` contains the following

<img width="286" alt="Screenshot 2023-03-20 at 2 21 46 PM" src="https://user-images.githubusercontent.com/23039961/226351907-26249332-b5bd-4668-8deb-c769622f5fac.png">


The `build.gradle` of the android library  is as follow

```
plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'org.csa.chiptools'
    compileSdk 33

    defaultConfig {
        minSdk 24
        targetSdk 33

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["../app/third_party/connectedhomeip/libs/jniLibs"]
        }
    }

    publishing {
        singleVariant('release') {}
    }
}

publishing {
    publications {
        chipTools(MavenPublication) {
            group = 'org.csa'
            artifactId = 'chip-tools-native'
            version = '1.0.0'
            afterEvaluate {
                from components.release
            }
        }
    }
}
```

Theoretically, it's possible to package the `.so` files as `jar` but it's requiring modifying the generated `pom.xml` to use a maven plugin in order to copy the `.so` files in the appropriate folders.

The other `Jars` can published as is, like you did (There are still remaining questions about packaging)

Disclaimer: I didn't setup the `repository` part of the publication. I'm publishing/consuming to/from my local maven repository.

**Comment by jonsmirl** [comment]
What about Apple's assertion that these CHIP libs need to be tested, certified and signed?  Shouldn't there be two repositories, one for the tested/certified/signed versions and another for the development version?

**Comment by tetedoie** [comment]
That's a good question. I'm assuming that CSA members will have to certify their application itself. If the libraries must be certified as well, it must be taken into account in the release process but we don't necessarily need separate repository (In the meantime, it's common practice to use a separate repository for [snapshot](https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version). Snapshot can also be published in the same maven repository). 

Ideally, I would like less human intervention as possible (from CI, triggering publication on git tag and creating git tag on merge). We could also, introduce a step that must be triggered manually by someone. For example, the CSA goes trought the certification process and triggering the publication when the certification passed. Alternatively, we might want to leverage the existing tags (There are TE_XX_XX (Test Event), SVE_XX_XX (Specification Validation Event)) and match them with "pre-release" versions (alpha, beta, rc..)

**Comment by jonsmirl** [comment]
Shouldn't Google maintain a test/certified/signed CHIP lib? How is a random Android developer going to deal with the library falling during testing of their app? The Android developer is responsible for the code in their app, but they can't deal with a library testing failure. On Apple the CHIP lib is a system library they provide, you don't embed it in your app.

**Comment by tetedoie** [comment]
> Shouldn't Google maintain a test/certified/signed CHIP lib?

It's hard to tell what Google should do in a distributed project like CHIP (Even if most of this code is implemented by Google, in my understanding, the CHIP repository is owned by the CSA org and the maven repository where those artifacts gonna be distributed, will also be owned by the CSA org). In the meantime, it would be interesting to know Google plans and strategy about this code. What I can tell is what I would expect as a developer consuming this code.

> How is a random Android developer going to deal with the library falling during testing of their app?

Android developers should only target `final` version of the artifacts (which would be certified and tested already) when submitting their app for testing. It's still not clear to me what would be the testing/certification process for an app.

> The Android developer is responsible for the code in their app, but they can't deal with a library testing failure.

I totally agree, it's why we need the artifacts to be distributed and versioned appropriately, so developers know that they are consuming a version which is tested and certified, and they can focus only on their own code. 

> On Apple the CHIP lib is a system library they provide, you don't embed it in your app.

It's hard to compare Google and Apple approach. Apple provide Matter APIs starting from iOS 16 without backward support but [according to them](https://developer.apple.com/support/app-store/) 72% of all iPhone are using iOS 16 so it's not a big deal. On Android, even if it became part of the OS, due to fragmentation, it'll represent a small percentage of market shares for quite some time.

**Comment by jonsmirl** [comment]
Could the Google Home app be used as a library distribution vehicle? In other words, by installing the Google Home app it would also install a certified shared library. The library doesn't have to be in the app, the app would signal the OS to install the shared library. Like an triggering the install of an optional piece of GPS?

**Comment by kuyu132** [comment]
> Personally, I'm open to any approach, but ideally I would like the Google Home App itself to not be involved. I mean, as a an app developer I don't want to have to force my users to install the Google Home App (or uninstall/reinstall it) in order to use my own application. In the other hand, the code could be distributed with GPS (there are existing mechanism to check APIs availability, force update GPS...).
> 
> The main advantage I see in letting developers manage the dependency on their own, is that they have full control over it, so they don't have to wait for a new version of GPS to get the last spec/features/fixes.
> 
> It would be great if Google could weight in the conversation to tell us their long/mid term plans.

Google's home library was released on December 15 last year. I couldn't find the latest version on the website. Do you have a library greater than version 16.0.0?

https://developers.google.com/android/guides/releases?hl=zh-cn

**Comment by jonsmirl** [comment]
Are there any updates on this?

**Comment by pierredelisle** [comment]
As of v2.0.0, we're pulling the Matter SDK (demo) libraries for Android from https://central.sonatype.com/artifact/com.google.matter/matter-android-demo-sdk/overview.

**Comment by kuyu132** [comment]
> As of v2.0.0, we're pulling the Matter SDK (demo) libraries for Android from https://central.sonatype.com/artifact/com.google.matter/matter-android-demo-sdk/overview.

This is matter's sdk, not google home's sdk
